const fs = require('fs');

module.exports = async function trainnlp(manager) {
  if (fs.existsSync('model.nlp')) {
    manager.load('model.nlp');
    return;
  }
  manager.addDocument('en', 'say about you', 'agent.whoami');
  manager.addDocument('en', 'why are you here', 'agent.whoami');
  manager.addDocument('en', 'what is your personality', 'agent.whoami');
  manager.addDocument('en', 'describe yourself', 'agent.whoami');
  manager.addDocument('en', 'tell me about yourself', 'agent.whoami');
  manager.addDocument('en', 'tell me about you', 'agent.whoami');
  manager.addDocument('en', 'what are you', 'agent.whoami');
  manager.addDocument('en', 'who are you', 'agent.whoami');
  manager.addDocument('en', 'i was abused', 'agent.askhelp');
  manager.addDocument('en', 'i was raped', 'agent.askhelp');
  manager.addDocument('en', 'i am feeling bad', 'agent.askhelp');
  manager.addDocument('en', 'i want help', 'agent.askhelp');
  manager.addDocument('en', 'help me please', 'agent.askhelp');
  manager.addDocument('en', 'sos', 'agent.askhelp');
  manager.addDocument('en', 'please i want urgent help', 'agent.askhelp');
  manager.addDocument('en', 'how can i', 'agent.guide');
  manager.addDocument('en', 'how to', 'agent.guide');
  manager.addDocument('en', 'how can i seek help', 'agent.guide');
  manager.addDocument('en', 'help guide', 'agent.guide');
  manager.addDocument('en', 'how to use help function', 'agent.guide');
  manager.addDocument('en', 'how to reach ngo', 'agent.guide');
  manager.addDocument('en', 'how to reach police', 'agent.guide');
  manager.addDocument('en', 'you have a bug', 'agent.foundbug');
  manager.addDocument('en', 'you are little buggy', 'agent.foundbug');
  manager.addDocument('en', 'you are not good', 'agent.foundbug');
  manager.addDocument('en', 'i have a problem with you', 'agent.foundbug');
  manager.addDocument('en', 'i found a bug', 'agent.foundbug');
  manager.addDocument('en', 'do you have any bugs', 'agent.foundbug');
  manager.addDocument('en', 'ha ha ha', 'agent.emotionshaha');
  manager.addDocument('en', 'lol', 'agent.emotionshaha');
  manager.addDocument('en', 'omg', 'agent.emotionshaha');
  manager.addDocument('en', 'wow thats amazing', 'agent.emotionshaha');
  manager.addDocument('en', 'incredible ha ha laugh wow', 'agent.emotionshaha');
  manager.addDocument('en', 'wow', 'agent.emotionshaha');
  manager.addDocument('en', 'thanks a lot', 'agent.thanks');
  manager.addDocument('en', 'thank you so much', 'agent.thanks');
  manager.addDocument('en', 'how may i thank you', 'agent.thanks');
  manager.addDocument('en', 'you are thank you', 'agent.thanks');
  manager.addDocument('en', 'what is abuse', 'agent.whatisabuse');
  manager.addDocument('en', 'is abuse criminal', 'agent.whatisabuse');
  manager.addDocument('en', 'what is rape', 'agent.whatisabuse');
  manager.addDocument('en', 'what is torture', 'agent.whatisabuse');
  manager.addDocument('en', 'why am i tortured', 'agent.whatisabuse');
  manager.addDocument('en', 'why was i abused', 'agent.whatisabuse');
  manager.addDocument('en', 'how are you', 'agent.howru');
  manager.addDocument('en', 'are you fine', 'agent.howru');
  manager.addDocument('en', 'are you doing good', 'agent.howru');
  manager.addDocument('en', 'good morning', 'agent.howru');
  manager.addDocument('en', 'what your mood', 'agent.howru');
  manager.addDocument('en', 'something new', 'agent.whatsnew');
  manager.addDocument('en', 'latest update', 'agent.whatsnew');
  manager.addDocument('en', 'what is in the latest update', 'agent.whatsnew');
  manager.addDocument('en', 'what new in this update', 'agent.whatsnew');
  manager.addDocument('en', 'can you give me some tips', 'agent.tips');
  manager.addDocument('en', 'what if i am abused', 'agent.tips');
  manager.addDocument('en', 'how to seek help', 'agent.tips');
  manager.addDocument('en', 'how can i fight', 'agent.tips');  

  const hrstart = process.hrtime();
  await manager.train();
  const hrend = process.hrtime(hrstart);
  console.info('Trained (hr): %ds %dms', hrend[0], hrend[1] / 1000000);
  console.log('Trained Successfully');

  manager.addAnswer('en', 'agent.whoami', "Hi, I am Saathi! I want to empower every person to open up their bad situations that occur whether at workplace or in public. We not only provide you support during the time you need us the most, but can also connect you with our partner NGO for human assistance and can also help report to legal authorities. If you have a friend in need, do spread the word about us. How else may I help you with?");
  manager.addAnswer('en', 'agent.guide', "With Saathi, you can seek help anytime from anywhere, with full privacy and security. To get started, just type 'I want help' or a 'hello' and follow the prompts. We will generate a 16 digit code for you, save it because you will need it for all future correspondence related to your case. Open up your feelings, and if you want then allow for a human assistance through our partner NGOs or legal assistance through police. We will ask for your email to contact you later, but that's totally optional. How else may I help you with?");
  manager.addAnswer('en', 'agent.askhelp', "Saathi is here to support you at the time of your need.");
  manager.addAnswer('en', 'agent.foundbug', "It's really disappointing to hear this. But, thank you for figuring one out. Please fill in the details in the contact form. We'll be glad to get back to you. Some of our valuable users stand a chance to win cool gifts! How else may I help you with?");
  manager.addAnswer('en', 'agent.emotionshaha', "It is great when I see you happy... What else can i help you with?");
  manager.addAnswer('en', 'agent.thanks', "You are always welcome... Well, What next you want to know?");
  manager.addAnswer('en', 'agent.whatisabuse', "We are on a mission to stop unreported abuses! Abuse is the violation of a being, unfair and unjust. Abuse can come in many forms, such as: physical or verbal maltreatment, injury, assault, violation, or any type of aggression. Its a criminal offence, and we strictly encourage everyone to report it. In case you want to seek help from us, please feel free - I am your Saathi.");
  manager.addAnswer('en', 'agent.howru', "I am doing great ! and hope you too... How may I help you today?");
  manager.addAnswer('en', 'agent.whatsnew', "Hey, I'm really glad to hear your voice! We continue to serve you better with every release. With this release we bring you some new voice design updates and updated varied responses. We've added some additional help options and our algorithm are more accurate. How may I help you today?");
  manager.addAnswer('en', 'agent.tips', "We are on a mission to deliver justice to every victim! We dont want bad things to happen with you, but unfortunately if it happens, we strongly encourage you to report it immediately. If its a workplace, report your HR. If its a school, talk to the incharge or if in a public place, get to police. Save evidences if you have. But keep in mind even when nobody hears you, we are always there to help you out. We can also connect you with our partner NGO for human assistance and can also help report to legal authorities. If you have a friend in need, do spread the word about us. If you wish to report now, please type a 'hello' or SOS. How may I help you today?");
  
  manager.save();
};